load("@npm_angular_bazel//:index.bzl", "ng_module")

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "window",
    srcs = ["window_module.ts"],
    deps = [
        "@npm//@angular/core"],
)
